
spring:
  datasource:
    url: jdbc:mysql://192.168.22.46:3306/sb002?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

file:
  path: file/**    #文件访问路径
  address:  C:/Users/96592/Desktop/0 #文件保存路径